---

name: CI

on:
  push:
    branches: [ main ]

env:
  AZURE_REGISTRY: flashyACR.azurecr.io
  AZURE_REPOSITORY: ${{ github.repository }}
  AZURE_TOKEN_NAME: ${{ github.event.repository.name }}

jobs:
  azure-work:
    runs-on: ubuntu-latest

    steps:
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Temporary TOKEN
        run: |
          echo "$AZURE_TOKEN_NAME=$(az acr token create --name $AZURE_TOKEN_NAME \
          --registry $AZURE_REGISTRY --repository ${AZURE_REPOSITORY,,} \
          content/write content/read --output json --only-show-errors \
          --expiration $(TZ=UTC date -d '15 mins' +%Y-%m-%dT%H:%M:%SZ) \
          --subscription ${{ secrets.AZURE_SUBSCRIPTION }} \
          | jq '.credentials.passwords[0].value')" >> GITHUB_ENV
      - name: Log out of Azure
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az logout
            az cache purge
            az account clear
      - name: Validate logout
        run: az account show | jq '.environmentName'
