---

name: CI

on:
  push:
    branches: [ main ]

env:
  AZURE_REGISTRY: flashyacr.azurecr.io
  AZURE_REPOSITORY: ${{ github.repository }}
  AZURE_TOKEN_NAME: ${{ github.event.repository.name }}

jobs:
  azure-work:
    runs-on: ubuntu-latest
    outputs:
      AZURE_TOKEN: ${{steps.token.outputs[env.AZURE_TOKEN_NAME]}}
    steps:
      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Temporary TOKEN
        id: token
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION }}
          AZURE_TOKEN=$(az acr token create \
          --name $AZURE_TOKEN_NAME --registry $AZURE_REGISTRY \
          --repository ${AZURE_REPOSITORY,,} content/write content/read \
          --output json --only-show-errors \
          --expiration $(TZ=UTC date -d '15 mins' +%Y-%m-%dT%H:%M:%SZ) \
          --subscription ${{ secrets.AZURE_SUBSCRIPTION }} \
          | jq '.credentials.passwords[0].value' | awk -F '"' '{print $2}')
          echo "AZURE_TOKEN=$AZURE_TOKEN" >> $GITHUB_ENV
          echo "::add-mask::$AZURE_TOKEN"
          echo "::set-output name=$AZURE_TOKEN_NAME::$AZURE_TOKEN"
      - name: Log out of Azure
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az logout
            az cache purge
            az account clear
      - name: Validate logout
        run: |
          az account show | jq '.environmentName'

  docker-work:
    needs: azure-work
    env:
      AZURE_TOKEN: ${{ needs.azure-work.outputs.AZURE_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Docker File
        run: printf "FROM alpine\nENTRYPOINT [ "bin/sh" ]" >> Dockerfile
      - name: Docker build
        run: |
          docker build . -t ${AZURE_REGISTRY,,}/${AZURE_REPOSITORY,,}
          az acr login --name ${AZURE_REGISTRY,,} --username $AZURE_TOKEN_NAME \
          -p $AZURE_TOKEN --only-show-errors
          docker push ${AZURE_REGISTRY,,}/${AZURE_REPOSITORY,,}


